### ISSUE TITLE
🐛 npm run dev

### ISSUE THREAD

**Issue by iconized** [ervin-sungkono/Portfolio-Website-v2#1]
Getting The following error while running `npm run dev` after `npm install`

```bash

> portofolio-web-v2@1.3 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/whoami/Documents/GitHub/Snigdha-OS.github.io/.env
event - compiled client and server successfully in 3.9s (175 modules)
wait  - compiling /404 (client and server)...
event - compiled client and server successfully in 1682 ms (508 modules)
Warning: <title> should not be used in _document.js's <Head>. https://nextjs.org/docs/messages/no-document-title
Warning: viewport meta tags should not be used in _document.js's <Head>. https://nextjs.org/docs/messages/no-document-viewport-meta
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
wait  - compiling / (client and server)...
event - compiled client and server successfully in 715 ms (577 modules)
Warning: <title> should not be used in _document.js's <Head>. https://nextjs.org/docs/messages/no-document-title
Warning: viewport meta tags should not be used in _document.js's <Head>. https://nextjs.org/docs/messages/no-document-viewport-meta
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
wait  - compiling /_error (client and server)...
error - lib/fetch.js (11:46) @ shots
error - TypeError: shots is not iterable
    at getDribbbleUserData (webpack-internal:///./lib/fetch.js:17:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getStaticProps (webpack-internal:///./pages/index.js:82:26)
    at async Object.renderToHTML (/home/whoami/Documents/GitHub/Snigdha-OS.github.io/node_modules/next/dist/server/render.js:385:20)
    at async doRender (/home/whoami/Documents/GitHub/Snigdha-OS.github.io/node_modules/next/dist/server/base-server.js:720:34)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/home/whoami/Documents/GitHub/Snigdha-OS.github.io/node_modules/next/dist/server/base-server.js:837:28)
    at async /home/whoami/Documents/GitHub/Snigdha-OS.github.io/node_modules/next/dist/server/response-cache/index.js:83:36 {
  page: '/'
}
   9 |         .then(res => res.json())
  10 |         .catch(error => console.log(error))
> 11 |         dribbbleShots = [...dribbbleShots, ...shots]
     |                                              ^
  12 |         page++
  13 |     }while(shots.length === per_page && !limit)
  14 |     return dribbbleShots ?? []
error - lib/fetch.js (11:46) @ shots
error - TypeError: shots is not iterable
    at getDribbbleUserData (webpack-internal:///./lib/fetch.js:17:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getStaticProps (webpack-internal:///./pages/index.js:82:26)
    at async Object.renderToHTML (/home/whoami/Documents/GitHub/Snigdha-OS.github.io/node_modules/next/dist/server/render.js:385:20)
    at async doRender (/home/whoami/Documents/GitHub/Snigdha-OS.github.io/node_modules/next/dist/server/base-server.js:720:34)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/home/whoami/Documents/GitHub/Snigdha-OS.github.io/node_modules/next/dist/server/base-server.js:837:28)
    at async /home/whoami/Documents/GitHub/Snigdha-OS.github.io/node_modules/next/dist/server/response-cache/index.js:83:36 {
  page: '/'
}
   9 |         .then(res => res.json())
  10 |         .catch(error => console.log(error))
> 11 |         dribbbleShots = [...dribbbleShots, ...shots]
     |                                              ^
  12 |         page++
  13 |     }while(shots.length === per_page && !limit)
  14 |     return dribbbleShots ?? []
event - compiled client and server successfully in 698 ms (578 modules)
Warning: <title> should not be used in _document.js's <Head>. https://nextjs.org/docs/messages/no-document-title
Warning: viewport meta tags should not be used in _document.js's <Head>. https://nextjs.org/docs/messages/no-document-viewport-meta
Warning: <title> should not be used in _document.js's <Head>. https://nextjs.org/docs/messages/no-document-title
Warning: viewport meta tags should not be used in _document.js's <Head>. https://nextjs.org/docs/messages/no-document-viewport-meta
Warning: <title> should not be used in _document.js's <Head>. https://nextjs.org/docs/messages/no-document-title
Warning: viewport meta tags should not be used in _document.js's <Head>. https://nextjs.org/docs/messages/no-document-viewport-meta
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
error - lib/fetch.js (11:46) @ shots
error - TypeError: shots is not iterable
    at getDribbbleUserData (webpack-internal:///./lib/fetch.js:17:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getStaticProps (webpack-internal:///./pages/index.js:82:26)
    at async Object.renderToHTML (/home/whoami/Documents/GitHub/Snigdha-OS.github.io/node_modules/next/dist/server/render.js:385:20)
    at async doRender (/home/whoami/Documents/GitHub/Snigdha-OS.github.io/node_modules/next/dist/server/base-server.js:720:34)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/home/whoami/Documents/GitHub/Snigdha-OS.github.io/node_modules/next/dist/server/base-server.js:837:28)
    at async /home/whoami/Documents/GitHub/Snigdha-OS.github.io/node_modules/next/dist/server/response-cache/index.js:83:36 {
  page: '/'
}
   9 |         .then(res => res.json())
  10 |         .catch(error => console.log(error))
> 11 |         dribbbleShots = [...dribbbleShots, ...shots]
     |                                              ^
  12 |         page++
  13 |     }while(shots.length === per_page && !limit)
  14 |     return dribbbleShots ?? []
Warning: <title> should not be used in _document.js's <Head>. https://nextjs.org/docs/messages/no-document-title
Warning: viewport meta tags should not be used in _document.js's <Head>. https://nextjs.org/docs/messages/no-document-viewport-meta
```

**Comment by iconized** [comment]
Fixed with `npm audit fix --force`

**Comment by ervin-sungkono** [comment]
Hello @iconized , sorry for the late response, please check if your dribble token env is set properly and test the API call to see if the proper response is being returned
